[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Partner "compat"
[[patches]]
[patches.pattern]
target = '=[SMODS partner "partner.lua"]'
pattern = '''G.FUNCS.run_setup_partners_option()'''
position = "at"
match_indent = true
payload = '''if not G.GAME.chdp_disabled_partner then G.FUNCS.run_setup_partners_option() end'''